import '@/styles/tailwind.css'

import type { Metadata } from 'next'
import type { FC, PropsWithChildren } from 'react'
import { ThemeProvider } from '@/components/components/theme-provider'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Toaster } from 'react-hot-toast'

export const metadata: Metadata = {
  title: 'SOS Alert',
  description: 'Generated by Next.js',
}

const Layout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <body className="min-h-screen bg-background antialiased">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <ScrollArea className="h-screen w-screen">{children}</ScrollArea>
      </ThemeProvider>

      <Toaster position="top-right" />
    </body>
  </html>
)

export default Layout
